aws_region         = "ap-south-1"
project_name       = "devops-project"
environment        = "prod"
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["ap-south-1a", "ap-south-1b"]
github_org         = "aryanjain6061"
kubernetes_version = "1.29"
node_instance_types = ["t3.medium"]
node_desired_size  = 2
node_min_size      = 1
node_max_size      = 5
